---
title: "Co-Kriging"
author: "YX"
date: "8/20/2020"
output:
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# [1] Read in librareis and input data
setwd("c:/Users/hpham/OneDrive - INTERA Inc/projects/012_rscript_geostats_s/scripts/")
source("get_input.R")

# [2] Choose a scenario to run
#cal_year <- "WL2019_minus_Shallow.Combined.1929"
#cal_year <- "WL2020_minus_Shallow.Combined.1929"
#cal_year <- "WL2019_minus_Shallow.Below.1929"
#cal_year <- "WL2020_minus_Shallow.Below.1929"

#cal_year <- "WL2019_3yr"
cal_year <- "WL2020_3yr"
#cal_year <- "shallow_below_2019_3yr"
#cal_year <- "shallow_below_2020_3yr"

thre_cutoff <- as.integer(200000)
thre_width <- as.integer(10000)

method_script_name <- "Co_Kriging_Topo_DEM" # OK_Water_Levels, Co_Kriging_GAM, Co_Kriging_Topo_Streams, Co_Kriging_Topo_DEM
method <- "Co_Kriging_Topo_DEM" # OK_Water_Levels, Co_Kriging_GAM, Co_Kriging_Topo_Streams

```


```{r}
# Prepare data
source("data_manipulation.R")
```

```{r}
# Choose an interpolation method
# [1]
source(paste(method_script_name,".R", sep=""))

# [2]
#source("Co_Kriging_GAM.R")

# [3]
#source("Co_Kriging_Topo_DEM.R")

# [4]
#source("Co_Kriging_Topo_Pumping.R")

# [5]
#source("Co_Kriging_Topo_Streams_Pumping.R")

# [6] 
#source("Co_Kriging_Topo_Streams.R")

```


```{r}
# extract values for each acquifer for cokriging with DEM
# create raster and write on file
#source("write_outputs.R")

```






























